import http from 'k6/http';
import { check, sleep } from 'k6';
import { AUTH_URL, COURSE_URL, ANALYTICS_URL, currentScenario, thresholds, headers } from './config.js';
import { randomString, randomIntBetween } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

export const options = {
  scenarios: {
    mixed_workload: currentScenario,
  },
  thresholds,
};

// Simulated Test Data
const ROLES = ['ONLINE_STUDENT', 'ONLINE_STUDENT', 'ONLINE_STUDENT', 'TEACHER', 'ADMIN'];

export default function () {
  // 1. Simulate a user arriving and logging in
  const role = ROLES[randomIntBetween(0, ROLES.length - 1)];
  const email = `testuser_${randomString(6)}@example.com`;
  const password = 'TestPassword123!';

  const registerRes = http.post(`${AUTH_URL}/api/auth/register`, JSON.stringify({
    name: 'Mixed Load User',
    email,
    password,
    role,
  }), { headers: headers() });

  if (registerRes.status !== 201) {
    // If register fails (e.g. rate limit), just return and wait
    sleep(1);
    return;
  }

  const loginRes = http.post(`${AUTH_URL}/api/auth/login`, JSON.stringify({
    email,
    password,
  }), { headers: headers() });

  const token = loginRes.json('token');
  if (!token) return;

  sleep(randomIntBetween(1, 3));

  if (role === 'ONLINE_STUDENT') {
    // Student Scenario
    // 1. Browse courses
    const coursesRes = http.get(`${COURSE_URL}/api/courses`, { headers: headers(token) });
    check(coursesRes, { 'courses fetched': (r) => r.status === 200 });
    
    sleep(randomIntBetween(2, 5));

    // 2. Fetch analytics overview
    const overviewRes = http.get(`${ANALYTICS_URL}/api/analytics/student/overview`, { headers: headers(token) });
    check(overviewRes, { 'student overview fetched': (r) => r.status === 200 || r.status === 404 });

  } else if (role === 'TEACHER') {
    // Teacher Scenario
    const teacherCourses = http.get(`${COURSE_URL}/api/courses/teacher`, { headers: headers(token) });
    check(teacherCourses, { 'teacher courses fetched': (r) => r.status === 200 });

    sleep(randomIntBetween(1, 3));

    // Create a dummy course
    const createRes = http.post(`${COURSE_URL}/api/courses`, JSON.stringify({
      title: `Load Test Course ${randomString(4)}`,
      description: 'A test course generated by k6',
      category: 'Math'
    }), { headers: headers(token) });
    check(createRes, { 'course created': (r) => r.status === 201 });

  } else if (role === 'ADMIN') {
    // Admin Scenario
    const adminOverview = http.get(`${ANALYTICS_URL}/api/analytics/admin/overview`, { headers: headers(token) });
    check(adminOverview, { 'admin overview fetched': (r) => r.status === 200 });
  }

  // Final sleep before the iteration ends
  sleep(randomIntBetween(3, 10));
}
